-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 12:04:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_sistema_estagios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_sistema_estagios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_sistema_estagios` DEFAULT CHARACTER SET utf8 ;
USE `bd_sistema_estagios` ;

-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_perfis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_perfis` (
  `id` INT(2) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `identificacao` VARCHAR(5) NULL,
  `status` TINYINT(1) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_contato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contato` VARCHAR(11) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `perfil` INT(2) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `matricula` VARCHAR(30) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `id_contato` INT UNSIGNED NOT NULL,
  `alterar_senha` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_tbl_perfis1_idx` (`perfil` ASC),
  INDEX `fk_tbl_usuario_tbl_contato1_idx` (`id_contato` ASC),
  CONSTRAINT `fk_usuario_tbl_perfis1`
    FOREIGN KEY (`perfil`)
    REFERENCES `bd_sistema_estagios`.`tbl_perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_usuario_tbl_contato1`
    FOREIGN KEY (`id_contato`)
    REFERENCES `bd_sistema_estagios`.`tbl_contato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_natureza_vinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_natureza_vinculo` (
  `idnatureza_vinculo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `carga_horaria_maxima` INT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idnatureza_vinculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_aluno` (
  `idusuario` INT UNSIGNED NOT NULL,
  `idnatureza_vinculo` INT UNSIGNED NOT NULL,
  `carga_horaria_cumprida` INT(3) NOT NULL DEFAULT 0,
  `periodo` INT(1) NULL,
  `data_cadastro` TIMESTAMP NULL,
  `data_modificacao` TIMESTAMP NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_aluno_natureza_vinculo1_idx` (`idnatureza_vinculo` ASC),
  CONSTRAINT `fk_aluno_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_sistema_estagios`.`tbl_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_natureza_vinculo1`
    FOREIGN KEY (`idnatureza_vinculo`)
    REFERENCES `bd_sistema_estagios`.`tbl_natureza_vinculo` (`idnatureza_vinculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_semestre_letivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_semestre_letivo` (
  `idsemestre_letivo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `semestre` INT(1) NOT NULL,
  `ano` INT(4) UNSIGNED NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idsemestre_letivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_empresa` (
  `idempresa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `inicio_vinculo` DATE NOT NULL,
  `final_vinculo` DATE NOT NULL,
  `contato` VARCHAR(14) NOT NULL,
  `email` VARCHAR(255) NULL,
  `cidade` VARCHAR(60) NULL,
  `bairro` VARCHAR(60) NULL,
  `endereco` VARCHAR(155) NULL,
  `cep` VARCHAR(10) NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_supervisor_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_supervisor_empresa` (
  `empresa_idempresa` INT UNSIGNED NOT NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`empresa_idempresa`, `usuario_idusuario`),
  INDEX `fk_empresa_has_usuario_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_empresa_has_usuario_empresa1_idx` (`empresa_idempresa` ASC),
  CONSTRAINT `fk_empresa_has_usuario_empresa1`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `bd_sistema_estagios`.`tbl_empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_has_usuario_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_sistema_estagios`.`tbl_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_estagio` (
  `idestagio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idusuario` INT UNSIGNED NOT NULL,
  `idsemestre_letivo` INT UNSIGNED NOT NULL,
  `idempresa` INT UNSIGNED NOT NULL,
  `idusuario_s` INT UNSIGNED NOT NULL,
  `area_de_atuacao` TEXT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE NOT NULL,
  `carga_horaria_total` INT(3) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idestagio`),
  INDEX `fk_estagio_aluno1_idx` (`idusuario` ASC),
  INDEX `fk_estagio_semestre_letivo1_idx` (`idsemestre_letivo` ASC),
  INDEX `fk_estagio_supervisor_empresa1_idx` (`idempresa` ASC, `idusuario_s` ASC),
  CONSTRAINT `fk_estagio_aluno1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_sistema_estagios`.`tbl_aluno` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_semestre_letivo1`
    FOREIGN KEY (`idsemestre_letivo`)
    REFERENCES `bd_sistema_estagios`.`tbl_semestre_letivo` (`idsemestre_letivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estagio_supervisor_empresa1`
    FOREIGN KEY (`idempresa` , `idusuario_s`)
    REFERENCES `bd_sistema_estagios`.`tbl_supervisor_empresa` (`empresa_idempresa` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_tipo_arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_tipo_arquivo` (
  `idtipo_arquivo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idtipo_arquivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_arquivo` (
  `idarquivo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idtipo_arquivo` INT UNSIGNED NOT NULL,
  `idestagio` INT UNSIGNED NOT NULL,
  `nome` TEXT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idarquivo`),
  INDEX `fk_arquivo_tipo_arquivo1_idx` (`idtipo_arquivo` ASC),
  INDEX `fk_tbl_arquivo_tbl_estagio1_idx` (`idestagio` ASC),
  CONSTRAINT `fk_arquivo_tipo_arquivo1`
    FOREIGN KEY (`idtipo_arquivo`)
    REFERENCES `bd_sistema_estagios`.`tbl_tipo_arquivo` (`idtipo_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_arquivo_tbl_estagio1`
    FOREIGN KEY (`idestagio`)
    REFERENCES `bd_sistema_estagios`.`tbl_estagio` (`idestagio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_menus` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_metodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_metodos` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `classe` VARCHAR(45) NOT NULL,
  `metodo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `apelido` VARCHAR(255) NOT NULL,
  `privado` TINYINT(1) NOT NULL,
  `data_criacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 139
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_menus_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_menus_itens` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `id_menu` BIGINT(20) NOT NULL,
  `id_metodo` BIGINT(20) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_menus_itens_tbl_menus1_idx` (`id_menu` ASC),
  INDEX `fk_tbl_menus_itens_tbl_metodos1_idx` (`id_metodo` ASC),
  CONSTRAINT `fk_tbl_menus_itens_tbl_menus1`
    FOREIGN KEY (`id_menu`)
    REFERENCES `bd_sistema_estagios`.`tbl_menus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_menus_itens_tbl_metodos1`
    FOREIGN KEY (`id_metodo`)
    REFERENCES `bd_sistema_estagios`.`tbl_metodos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_permissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_permissoes` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_perfil` INT(2) NOT NULL,
  `id_metodo` BIGINT(20) NOT NULL,
  `data_cadastro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`, `id_perfil`, `id_metodo`),
  INDEX `fk_tbl_perfis_has_tbl_metodos_tbl_metodos1_idx` (`id_metodo` ASC),
  INDEX `fk_tbl_perfis_has_tbl_metodos_tbl_perfis1_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_tbl_perfis_has_tbl_metodos_tbl_perfis1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `bd_sistema_estagios`.`tbl_perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_perfis_has_tbl_metodos_tbl_metodos1`
    FOREIGN KEY (`id_metodo`)
    REFERENCES `bd_sistema_estagios`.`tbl_metodos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_arquivos_necessarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_arquivos_necessarios` (
  `idnatureza_vinculo` INT UNSIGNED NOT NULL,
  `idtipo_arquivo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idnatureza_vinculo`, `idtipo_arquivo`),
  INDEX `fk_natureza_vinculo_has_tipo_arquivo_tipo_arquivo1_idx` (`idtipo_arquivo` ASC),
  INDEX `fk_natureza_vinculo_has_tipo_arquivo_natureza_vinculo1_idx` (`idnatureza_vinculo` ASC),
  CONSTRAINT `fk_natureza_vinculo_has_tipo_arquivo_natureza_vinculo1`
    FOREIGN KEY (`idnatureza_vinculo`)
    REFERENCES `bd_sistema_estagios`.`tbl_natureza_vinculo` (`idnatureza_vinculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_natureza_vinculo_has_tipo_arquivo_tipo_arquivo1`
    FOREIGN KEY (`idtipo_arquivo`)
    REFERENCES `bd_sistema_estagios`.`tbl_tipo_arquivo` (`idtipo_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_responsavel_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_responsavel_aluno` (
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  `aluno_usuario_idusuario` INT UNSIGNED NOT NULL,
  `tipo_responsavel` TINYINT(1) NOT NULL,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`usuario_idusuario`, `aluno_usuario_idusuario`),
  INDEX `fk_usuario_has_aluno_aluno1_idx` (`aluno_usuario_idusuario` ASC),
  INDEX `fk_usuario_has_aluno_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_aluno_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bd_sistema_estagios`.`tbl_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_aluno_aluno1`
    FOREIGN KEY (`aluno_usuario_idusuario`)
    REFERENCES `bd_sistema_estagios`.`tbl_aluno` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_vagas` (
  `idtbl_vagas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idempresa` INT UNSIGNED NOT NULL,
  `titulo` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idtbl_vagas`),
  INDEX `fk_tbl_vagas_empresa1_idx` (`idempresa` ASC),
  CONSTRAINT `fk_tbl_vagas_empresa1`
    FOREIGN KEY (`idempresa`)
    REFERENCES `bd_sistema_estagios`.`tbl_empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_sistema_estagios`.`tbl_mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_sistema_estagios`.`tbl_mensagem` (
  `idusuario1` INT UNSIGNED NOT NULL,
  `idusuario2` INT UNSIGNED NOT NULL,
  `mensagem` VARCHAR(255) NOT NULL,
  `data_envio` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_visualizacao` TIMESTAMP NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `data_cadastro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `data_modificacao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idusuario1`, `idusuario2`),
  INDEX `fk_tbl_usuario_has_tbl_usuario_tbl_usuario2_idx` (`idusuario2` ASC),
  INDEX `fk_tbl_usuario_has_tbl_usuario_tbl_usuario1_idx` (`idusuario1` ASC),
  CONSTRAINT `fk_tbl_usuario_has_tbl_usuario_tbl_usuario1`
    FOREIGN KEY (`idusuario1`)
    REFERENCES `bd_sistema_estagios`.`tbl_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_usuario_has_tbl_usuario_tbl_usuario2`
    FOREIGN KEY (`idusuario2`)
    REFERENCES `bd_sistema_estagios`.`tbl_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
